// COMPLETE FEMA RAPT LAYERS - 121 layers extracted from the actual RAPT tool
// Generated from comprehensive analysis of FEMA RAPT at https://experience.arcgis.com/experience/0a317e8998534c30a9b2d3861c814d42/

export interface FEMARAPTLayer {
  id: string
  name: string
  category: string
  serviceUrl: string
  serviceType: 'MapServer' | 'FeatureServer'
  status: string
  availability: 'working' | 'slow' | 'broken'
  description: string
}

export const FEMA_RAPT_LAYERS: FEMARAPTLayer[] = [
  // Infrastructure - CORRECTED LAYER INDICES AND URLS
  { id: 'fire-stations', name: 'Fire Stations', category: 'Infrastructure', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Medical_Emergency_Response_v1/FeatureServer/2', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Fire station and EMS locations across the United States' },
  { id: 'hospitals', name: 'Hospitals', category: 'Healthcare', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Medical_Emergency_Response_v1/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Hospital and medical center locations' },
  { id: 'law-enforcement', name: 'Local Law Enforcement Locations', category: 'Public Safety', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Law_Enforcement_v1/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Police stations and law enforcement facilities' },
  { id: 'prison-boundaries', name: 'Prison Boundaries', category: 'Public Safety', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Law_Enforcement_v1/FeatureServer/1', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Prisons and correctional facility locations' },
  { id: 'mobile-home-parks', name: 'Mobile Home Parks', category: 'Vulnerable Populations', serviceUrl: 'https://maps.nccs.nasa.gov/mapping/rest/services/hifld_open/public_venues/FeatureServer/3', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Mobile home park locations for vulnerable population analysis (HIFLD data via NASA NCCS)' },
  { id: 'public-schools', name: 'Public Schools', category: 'Education', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/ArcGIS/rest/services/HIFLD_Public_Schools_Placekey/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Public school locations from HIFLD database' },
  { id: 'private-schools', name: 'All Schools (K-12)', category: 'Education', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Education_v1/FeatureServer/2', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'All K-12 school locations including public and private' },
  { id: 'transmission-lines', name: 'Transmission Lines', category: 'Energy Infrastructure', serviceUrl: 'https://services1.arcgis.com/Hp6G80Pky0om7QvQ/arcgis/rest/services/Electric_Power_Transmission_Lines/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Electric power transmission lines' },
  { id: 'power-plants', name: 'Power Plants', category: 'Energy Infrastructure', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Power_Plants_in_the_US/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Power generation facilities' },
  { id: 'colleges-universities', name: 'Colleges and Universities', category: 'Education', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Education_v1/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Higher education institutions' },
  { id: 'snap-retailers', name: 'SNAP Authorized Retailers', category: 'Food Security', serviceUrl: 'https://services1.arcgis.com/RLQu0rK7h4kbsBq5/arcgis/rest/services/snap_retailer_location_data/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'SNAP authorized food retailers from USDA FNS' },
  { id: 'ambulance-services', name: 'Ambulance Services', category: 'Healthcare', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Medical_Emergency_Response_v1/FeatureServer/1', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Ambulance and emergency medical services' },
  { id: 'nursing-homes', name: 'Nursing Homes', category: 'Healthcare', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Medical_Emergency_Response_v1/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Nursing home and long-term care facilities' },
  { id: 'urgent-care', name: 'Urgent Care Facilities', category: 'Healthcare', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Medical_Emergency_Response_v1/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Urgent care medical facilities' },
  { id: 'dialysis-centers', name: 'Dialysis Centers (RxOpen)', category: 'Healthcare', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/HIFLD_Healthcare_Facilities_v1/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Dialysis treatment centers' },
  { id: 'pharmacies', name: 'Pharmacies (HIFLD)', category: 'Healthcare', serviceUrl: 'https://maps.nccs.nasa.gov/mapping/rest/services/hifld_open/public_health/FeatureServer/2', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Pharmacy locations from HIFLD data' },
  { id: 'places-worship', name: 'All Places Of Worship', category: 'Community', serviceUrl: 'https://maps.nccs.nasa.gov/mapping/rest/services/hifld_open/public_venues/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Religious facilities and places of worship (HIFLD data via NASA NCCS)' },
  { id: 'colleges-universities-fema', name: 'Colleges and Universities (FEMA)', category: 'Education', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Education_v1/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Higher education institutions from FEMA database' },
  { id: 'technical-trade-schools', name: 'Technical and Trade Schools', category: 'Education', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Education_v1/FeatureServer/1', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Technical and trade school locations' },
  { id: 'public-health-depts', name: 'Public Health Departments', category: 'Healthcare', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Structures_Medical_Emergency_Response_v1/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Public health department locations' },
  { id: 'wastewater-plants', name: 'Wastewater Treatment Plants (FRS)', category: 'Environmental', serviceUrl: 'https://services.arcgis.com/cJ9YHowT8TU7DUyn/ArcGIS/rest/services/FRS_Wastewater/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'EPA Facility Registry Service wastewater treatment plants' },
  { id: 'principal-ports', name: 'Principal Ports', category: 'Transportation', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Principal_Ports/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Major port facilities' },
  { id: 'high-hazard-dams', name: 'NID - High Hazard Potential Dam Lines', category: 'Critical Infrastructure', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Dams/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'National Inventory of Dams - High hazard potential dam lines' },
  
  // Hazards - Wildfire
  { id: 'current-wildfires-points', name: 'IRWIN - Wildfires - Current Incidents (Points)', category: 'Hazards - Wildfire', serviceUrl: 'https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/USA_Wildfires_v1/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Current wildfire incident point locations from IRWIN' },
  { id: 'current-wildfires-perimeters', name: 'NIFC - Wildfires - Current Incidents (Perimeters)', category: 'Hazards - Wildfire', serviceUrl: 'https://services3.arcgis.com/T4QMspbfLg3qTGWY/arcgis/rest/services/Current_WildlandFire_Perimeters/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Current wildfire perimeters from NIFC (zoom dependent)' },
  
  // Hazards - Flood
  { id: 'fema-flood-hazard', name: 'FEMA - Flood Hazard', category: 'Hazards - Flood', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/ArcGIS/rest/services/USA_Flood_Hazard_Reduced_Set_gdb/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'FEMA National Flood Hazard Layer (zoom dependent)' },
  { id: 'river-gauges', name: 'NOAA - River Gauges', category: 'Hazards - Flood', serviceUrl: 'https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/obs_meteocean_insitu_sfc_time/MapServer/6', serviceType: 'MapServer', status: 'Active', availability: 'broken', description: 'NOAA river gauge monitoring stations (zoom dependent)' },
  
  // Hazards - Earthquake
  { id: 'seismic-hazard', name: '2023 USGS National Seismic Hazard Model', category: 'Hazards - Earthquake', serviceUrl: 'https://earthquake.usgs.gov/arcgis/rest/services/eq/hazard2023/MapServer/0', serviceType: 'MapServer', status: 'Active', availability: 'broken', description: '2023 USGS National Seismic Hazard Model' },
  
  // Hazards - Multi-Hazard
  { id: 'national-risk-index', name: 'National Risk Index Census Tracts', category: 'Hazards - Multi-Hazard', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_National_Risk_Index/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'National Risk Index by census tract (zoom dependent)' },
  
  // Hazards - Tornado
  { id: 'tornado-tracks', name: 'NOAA - Historical Tornado Tracks: 1950-2017', category: 'Hazards - Tornado', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/Tornado_Tracks_1950_2017_1/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Historical tornado tracks from 1950-2017' },
  
  // Hazards - Hurricane
  { id: 'hurricane-tracks', name: 'NOAA - Hurricane Tracks (Recent)', category: 'Hazards - Hurricane', serviceUrl: 'https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/Recent_Hurricanes_v1/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Recent hurricane tracks and positions from NHC' },
  { id: 'tropical-weather', name: 'NHC - Tropical Weather Summary', category: 'Hazards - Hurricane', serviceUrl: 'https://services9.arcgis.com/RHVPKKiFTONKtxq3/arcgis/rest/services/NHC_Tropical_Weather_Summary_v1/MapServer/0', serviceType: 'MapServer', status: 'Active', availability: 'broken', description: 'National Hurricane Center tropical weather summary' },
  
  // Weather Services
  { id: 'weather-radar', name: 'NWS - NEXRAD Real-Time Weather Radar', category: 'Weather', serviceUrl: 'https://mapservices.weather.noaa.gov/eventdriven/rest/services/radar/radar_base_reflectivity_time/ImageServer', serviceType: 'MapServer', status: 'Active', availability: 'working', description: 'Real-time NEXRAD weather radar' },
  { id: 'watches-warnings', name: 'NWS - Watches and Warnings', category: 'Weather', serviceUrl: 'https://mapservices.weather.noaa.gov/eventdriven/rest/services/WWA/watch_warn_adv/MapServer', serviceType: 'MapServer', status: 'Active', availability: 'working', description: 'Current NWS watches and warnings' },
  { id: 'weather-outlooks', name: 'NWS - Weather Hazard Outlooks', category: 'Weather', serviceUrl: 'https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/forecast_meteoceanhydro_sfc_time/MapServer/1', serviceType: 'MapServer', status: 'Active', availability: 'broken', description: 'Weather hazard outlooks' },
  { id: 'severe-weather-outlook', name: 'NWS - Severe Weather Outlook', category: 'Weather', serviceUrl: 'https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/forecast_meteoceanhydro_sfc_time/MapServer/0', serviceType: 'MapServer', status: 'Active', availability: 'broken', description: 'Severe weather outlook forecasts' },
  { id: 'excessive-rainfall', name: 'NWS - Excessive Rainfall Outlook', category: 'Weather', serviceUrl: 'https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/forecast_meteoceanhydro_sfc_time/MapServer/2', serviceType: 'MapServer', status: 'Active', availability: 'broken', description: 'Excessive rainfall outlook' },
  { id: 'fire-weather', name: 'NWS - Fire Weather Outlooks', category: 'Weather', serviceUrl: 'https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/forecast_meteoceanhydro_sfc_time/MapServer/3', serviceType: 'MapServer', status: 'Active', availability: 'broken', description: 'Fire weather outlook forecasts' },
  { id: 'precipitation-forecast', name: 'NWS - Quantitative Precipitation Forecast (QPF)', category: 'Weather', serviceUrl: 'https://nowcoast.noaa.gov/arcgis/rest/services/nowcoast/forecast_meteoceanhydro_sfc_time/MapServer/2', serviceType: 'MapServer', status: 'Active', availability: 'broken', description: 'Quantitative precipitation forecasts' },
  
  // Demographics - County Level
  { id: 'county-population', name: 'Population (Total)', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Total population by county' },
  { id: 'county-housing-units', name: 'Housing Units (Total)', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Total housing units by county' },
  { id: 'county-households', name: 'Households (Total)', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Total households by county' },
  { id: 'county-pop-density', name: 'Population per Square Mile', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population density per square mile by county' },
  { id: 'county-under5', name: 'Under 5 years', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population under 5 years by county' },
  { id: 'county-65plus', name: '65 Years and Over', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population 65 years and over by county' },
  { id: 'county-black', name: 'Black or African American', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Black or African American population by county' },
  { id: 'county-hispanic', name: 'Hispanic or Latino', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Hispanic or Latino population by county' },
  { id: 'county-asian', name: 'Asian', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Asian population by county' },
  { id: 'county-native', name: 'American Indian and Alaska Native', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'American Indian and Alaska Native population by county' },
  { id: 'county-disability', name: 'With a Disability', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population with a disability by county' },
  { id: 'county-no-vehicle', name: 'No Vehicle Available', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Households with no vehicle available by county' },
  { id: 'county-mobile-homes', name: 'Mobile Homes', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Mobile home units by county' },
  { id: 'county-limited-english', name: 'Speak English "Less than Well"', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population speaking English less than well by county' },
  { id: 'county-no-internet', name: 'No Internet Access', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Households without internet access by county' },
  { id: 'county-no-computer', name: 'No Computer', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Households without a computer by county' },
  { id: 'county-unemployment', name: 'Unemployment Rate', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Unemployment rate by county' },
  { id: 'county-poverty', name: 'Below Poverty Level', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population below poverty level by county' },
  { id: 'county-no-insurance', name: 'No Health Insurance Coverage', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population without health insurance by county' },
  { id: 'county-median-income', name: 'Median Household Income', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Median household income by county' },
  { id: 'county-per-capita-income', name: 'Per Capita Income', category: 'County Demographics', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Per capita income by county' },
  { id: 'county-social-vulnerability', name: 'Social Vulnerability Index', category: 'County Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Social_Vulnerability_Index/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'CDC Social Vulnerability Index by county' },
  { id: 'county-svi-socioeconomic', name: 'SVI - Socioeconomic Status', category: 'County Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Social_Vulnerability_Index/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Social Vulnerability Index - Socioeconomic theme by county' },
  { id: 'county-svi-household', name: 'SVI - Household Characteristics', category: 'County Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Social_Vulnerability_Index/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Social Vulnerability Index - Household characteristics theme by county' },
  { id: 'county-svi-minority', name: 'SVI - Racial & Ethnic Minority Status', category: 'County Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Social_Vulnerability_Index/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Social Vulnerability Index - Minority status theme by county' },
  { id: 'county-svi-housing', name: 'SVI - Housing Type & Transportation', category: 'County Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Social_Vulnerability_Index/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Social Vulnerability Index - Housing and transportation theme by county' },
  
  // Demographics - Census Tract Level
  { id: 'tract-population', name: 'Population (Total)', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Total population by census tract' },
  { id: 'tract-housing-units', name: 'Housing Units (Total)', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Total housing units by census tract' },
  { id: 'tract-households', name: 'Households (Total)', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Total households by census tract' },
  { id: 'tract-pop-density', name: 'Population per Square Mile', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population density per square mile by census tract' },
  { id: 'tract-under5', name: 'Under 5 years', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population under 5 years by census tract' },
  { id: 'tract-65plus', name: '65 Years and Over', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population 65 years and over by census tract' },
  { id: 'tract-disability', name: 'With a Disability', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population with a disability by census tract' },
  { id: 'tract-no-vehicle', name: 'No Vehicle Available', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Households with no vehicle available by census tract' },
  { id: 'tract-mobile-homes', name: 'Mobile Homes', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Mobile home units by census tract' },
  { id: 'tract-limited-english', name: 'Speak English "Less than Well"', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population speaking English less than well by census tract' },
  { id: 'tract-poverty', name: 'Below Poverty Level', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Population below poverty level by census tract' },
  { id: 'tract-median-income', name: 'Median Household Income', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Median household income by census tract' },
  { id: 'tract-per-capita-income', name: 'Per Capita Income', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'Per capita income by census tract' },
  { id: 'tract-social-vulnerability', name: 'Social Vulnerability Index', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Social_Vulnerability_Index_Tract/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'CDC Social Vulnerability Index by census tract' },
  { id: 'tract-svi-socioeconomic', name: 'SVI - Socioeconomic Status', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Social_Vulnerability_Index_Tract/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Social Vulnerability Index - Socioeconomic theme by census tract' },
  { id: 'tract-svi-household', name: 'SVI - Household Characteristics', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Social_Vulnerability_Index_Tract/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Social Vulnerability Index - Household characteristics theme by census tract' },
  { id: 'tract-svi-minority', name: 'SVI - Racial & Ethnic Minority Status', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Social_Vulnerability_Index_Tract/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Social Vulnerability Index - Minority status theme by census tract' },
  { id: 'tract-svi-housing', name: 'SVI - Housing Type & Transportation', category: 'Tract Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Social_Vulnerability_Index_Tract/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Social Vulnerability Index - Housing and transportation theme by census tract' },
  
  // Demographics - Tribal Level  
  { id: 'tribal-population', name: 'Population (Total)', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Total population in tribal areas' },
  { id: 'tribal-housing-units', name: 'Housing Units (Total)', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Total housing units in tribal areas' },
  { id: 'tribal-households', name: 'Households (Total)', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Total households in tribal areas' },
  { id: 'tribal-pop-density', name: 'Population per Square Mile', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Population density per square mile in tribal areas' },
  { id: 'tribal-under5', name: 'Under 5 years', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Population under 5 years in tribal areas' },
  { id: 'tribal-65plus', name: '65 Years and Over', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Population 65 years and over in tribal areas' },
  { id: 'tribal-disability', name: 'With a Disability', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Population with a disability in tribal areas' },
  { id: 'tribal-no-vehicle', name: 'No Vehicle Available', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Households with no vehicle available in tribal areas' },
  { id: 'tribal-mobile-homes', name: 'Mobile Homes', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Mobile home units in tribal areas' },
  { id: 'tribal-limited-english', name: 'Speak English "Less than Well"', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Population speaking English less than well in tribal areas' },
  { id: 'tribal-no-internet', name: 'No Internet Access', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Households without internet access in tribal areas' },
  { id: 'tribal-no-computer', name: 'No Computer', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Households without a computer in tribal areas' },
  { id: 'tribal-unemployment', name: 'Unemployment Rate', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Unemployment rate in tribal areas' },
  { id: 'tribal-poverty', name: 'Below Poverty Level', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Population below poverty level in tribal areas' },
  { id: 'tribal-no-insurance', name: 'No Health Insurance Coverage', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Population without health insurance in tribal areas' },
  { id: 'tribal-median-income', name: 'Median Household Income', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Median household income in tribal areas' },
  { id: 'tribal-per-capita-income', name: 'Per Capita Income', category: 'Tribal Demographics', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Per capita income in tribal areas' },
  
  // Boundaries
  { id: 'state-boundaries', name: 'USA States (Generalized)', category: 'Boundaries', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_States_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'U.S. state boundaries' },
  { id: 'county-boundaries', name: 'USA Counties', category: 'Boundaries', serviceUrl: 'https://services2.arcgis.com/FiaPA4ga0iQKduv3/arcgis/rest/services/US_Counties_Territories/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'U.S. county boundaries' },
  { id: 'tribal-boundaries', name: 'Tribal Boundaries', category: 'Boundaries', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Tribal_Areas/FeatureServer/0', serviceType: 'FeatureServer', status: 'Active', availability: 'broken', description: 'Federally recognized tribal boundaries' },
  { id: 'census-tract-boundaries', name: 'Census Tract Boundaries', category: 'Boundaries', serviceUrl: 'https://services.arcgis.com/P3ePLMYs2RVChkJx/arcgis/rest/services/USA_Census_Tracts/FeatureServer', serviceType: 'FeatureServer', status: 'Active', availability: 'working', description: 'U.S. Census tract boundaries' }
]

// Export categories for easy filtering
export const FEMA_RAPT_CATEGORIES = [
  'Infrastructure',
  'Healthcare', 
  'Public Safety',
  'Vulnerable Populations',
  'Education',
  'Energy Infrastructure',
  'Food Security',
  'Community',
  'Environmental',
  'Transportation',
  'Critical Infrastructure',
  'Hazards - Wildfire',
  'Hazards - Flood',
  'Hazards - Earthquake',
  'Hazards - Multi-Hazard',
  'Hazards - Tornado',
  'Hazards - Hurricane',
  'Weather',
  'County Demographics',
  'Tract Demographics',
  'Tribal Demographics',
  'Boundaries'
]

// Helper function to get layers by category
export function getFEMARAPTLayersByCategory(category: string): FEMARAPTLayer[] {
  return FEMA_RAPT_LAYERS.filter(layer => layer.category === category)
}

// Helper function to search layers
export function searchFEMARAPTLayers(query: string): FEMARAPTLayer[] {
  const lowerQuery = query.toLowerCase()
  return FEMA_RAPT_LAYERS.filter(layer => 
    layer.name.toLowerCase().includes(lowerQuery) ||
    layer.description.toLowerCase().includes(lowerQuery) ||
    layer.category.toLowerCase().includes(lowerQuery)
  )
}